// <auto-generated />
using System;
using LMSDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603123435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMSDashboard.Models.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BetaUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ProdUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("StatusChangedAt");

                    b.HasIndex("Track");

                    b.HasIndex("Type");

                    b.ToTable("ContentItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            BetaUploadedAt = new DateTime(2026, 5, 2, 1, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 1 for demo",
                            Status = "InBeta",
                            StatusChangedAt = new DateTime(2026, 5, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 1",
                            Track = "B1",
                            Type = "Reading"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            BetaUploadedAt = new DateTime(2026, 5, 3, 2, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 2, 2, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 2 for demo",
                            Status = "Validated",
                            StatusChangedAt = new DateTime(2026, 5, 2, 2, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 2",
                            Track = "Advanced",
                            Type = "Audio",
                            ValidatedAt = new DateTime(2026, 5, 4, 2, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            BetaUploadedAt = new DateTime(2026, 5, 4, 3, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 3 for demo",
                            ProdUploadedAt = new DateTime(2026, 5, 6, 3, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProduction",
                            StatusChangedAt = new DateTime(2026, 5, 3, 3, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 3",
                            Track = "Applied",
                            Type = "PPT",
                            ValidatedAt = new DateTime(2026, 5, 5, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            BetaUploadedAt = new DateTime(2026, 5, 5, 4, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 4, 4, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 4 for demo",
                            Status = "Failed",
                            StatusChangedAt = new DateTime(2026, 5, 4, 4, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 4",
                            Track = "Crescent",
                            Type = "Activity",
                            ValidatedAt = new DateTime(2026, 5, 6, 4, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 5, 5, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 5 for demo",
                            Status = "Pending",
                            StatusChangedAt = new DateTime(2026, 5, 5, 5, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 5",
                            Track = "Foundation",
                            Type = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            BetaUploadedAt = new DateTime(2026, 5, 7, 6, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 6 for demo",
                            Status = "InBeta",
                            StatusChangedAt = new DateTime(2026, 5, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 6",
                            Track = "B1",
                            Type = "Reading"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            BetaUploadedAt = new DateTime(2026, 5, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 7, 7, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 7 for demo",
                            Status = "Validated",
                            StatusChangedAt = new DateTime(2026, 5, 7, 7, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 7",
                            Track = "Advanced",
                            Type = "Audio",
                            ValidatedAt = new DateTime(2026, 5, 9, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            BetaUploadedAt = new DateTime(2026, 5, 9, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 8 for demo",
                            ProdUploadedAt = new DateTime(2026, 5, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProduction",
                            StatusChangedAt = new DateTime(2026, 5, 8, 8, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 8",
                            Track = "Applied",
                            Type = "PPT",
                            ValidatedAt = new DateTime(2026, 5, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            BetaUploadedAt = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 9 for demo",
                            Status = "Failed",
                            StatusChangedAt = new DateTime(2026, 5, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 9",
                            Track = "Crescent",
                            Type = "Activity",
                            ValidatedAt = new DateTime(2026, 5, 11, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 10 for demo",
                            Status = "Pending",
                            StatusChangedAt = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 10",
                            Track = "Foundation",
                            Type = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            BetaUploadedAt = new DateTime(2026, 5, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 11 for demo",
                            Status = "InBeta",
                            StatusChangedAt = new DateTime(2026, 5, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 11",
                            Track = "B1",
                            Type = "Reading"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            BetaUploadedAt = new DateTime(2026, 5, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 12 for demo",
                            Status = "Validated",
                            StatusChangedAt = new DateTime(2026, 5, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 12",
                            Track = "Advanced",
                            Type = "Audio",
                            ValidatedAt = new DateTime(2026, 5, 14, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            BetaUploadedAt = new DateTime(2026, 5, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 13 for demo",
                            ProdUploadedAt = new DateTime(2026, 5, 16, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProduction",
                            StatusChangedAt = new DateTime(2026, 5, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 13",
                            Track = "Applied",
                            Type = "PPT",
                            ValidatedAt = new DateTime(2026, 5, 15, 13, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            BetaUploadedAt = new DateTime(2026, 5, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 14 for demo",
                            Status = "Failed",
                            StatusChangedAt = new DateTime(2026, 5, 14, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 14",
                            Track = "Crescent",
                            Type = "Activity",
                            ValidatedAt = new DateTime(2026, 5, 16, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 5, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 15 for demo",
                            Status = "Pending",
                            StatusChangedAt = new DateTime(2026, 5, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 15",
                            Track = "Foundation",
                            Type = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            BetaUploadedAt = new DateTime(2026, 5, 17, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 16 for demo",
                            Status = "InBeta",
                            StatusChangedAt = new DateTime(2026, 5, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 16",
                            Track = "B1",
                            Type = "Reading"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            BetaUploadedAt = new DateTime(2026, 5, 18, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 17 for demo",
                            Status = "Validated",
                            StatusChangedAt = new DateTime(2026, 5, 17, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 17",
                            Track = "Advanced",
                            Type = "Audio",
                            ValidatedAt = new DateTime(2026, 5, 19, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            BetaUploadedAt = new DateTime(2026, 5, 19, 18, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "alice@nxtwave.in",
                            Difficulty = "Easy",
                            IsDeleted = false,
                            Notes = "Seeded item 18 for demo",
                            ProdUploadedAt = new DateTime(2026, 5, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProduction",
                            StatusChangedAt = new DateTime(2026, 5, 18, 18, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 18",
                            Track = "Applied",
                            Type = "PPT",
                            ValidatedAt = new DateTime(2026, 5, 20, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            BetaUploadedAt = new DateTime(2026, 5, 20, 19, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 5, 19, 19, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "bob@nxtwave.in",
                            Difficulty = "Medium",
                            IsDeleted = false,
                            Notes = "Seeded item 19 for demo",
                            Status = "Failed",
                            StatusChangedAt = new DateTime(2026, 5, 19, 19, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 19",
                            Track = "Crescent",
                            Type = "Activity",
                            ValidatedAt = new DateTime(2026, 5, 21, 19, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 5, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "carol@nxtwave.in",
                            Difficulty = "Hard",
                            IsDeleted = false,
                            Notes = "Seeded item 20 for demo",
                            Status = "Pending",
                            StatusChangedAt = new DateTime(2026, 5, 20, 20, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sample Content Item 20",
                            Track = "Foundation",
                            Type = "Quiz"
                        });
                });

            modelBuilder.Entity("LMSDashboard.Models.JobRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JobRecords");
                });

            modelBuilder.Entity("LMSDashboard.Models.ReportCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReportKey")
                        .IsUnique();

                    b.ToTable("ReportCaches");
                });

            modelBuilder.Entity("LMSDashboard.Models.SyncLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SyncedAt");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("LMSDashboard.Models.ValidationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.ToTable("ValidationLogs");
                });

            modelBuilder.Entity("LMSDashboard.Models.ValidationLog", b =>
                {
                    b.HasOne("LMSDashboard.Models.ContentItem", "ContentItem")
                        .WithMany("ValidationLogs")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("LMSDashboard.Models.ContentItem", b =>
                {
                    b.Navigation("ValidationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
