// <auto-generated />
using System;
using LMSDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMSDashboard.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("LMSDashboard.Models.ContentItem", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("BetaUploadedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Difficulty").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<bool>("IsDeleted").HasColumnType("bit");
            b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
            b.Property<DateTime?>("ProdUploadedAt").HasColumnType("datetime2");
            b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(450)");
            b.Property<DateTime?>("StatusChangedAt").HasColumnType("datetime2");
            b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Track").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Type").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<DateTime?>("ValidatedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.ToTable("ContentItems");
        });

        modelBuilder.Entity("LMSDashboard.Models.ValidationLog", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CheckedAt").HasColumnType("datetime2");
            b.Property<Guid>("ContentItemId").HasColumnType("uniqueidentifier");
            b.Property<string>("Message").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<string>("Result").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("RuleName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.HasKey("Id");
            b.HasIndex("ContentItemId");
            b.ToTable("ValidationLogs");
        });
#pragma warning restore 612, 618
    }
}
